version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9000:9000
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    ports:
      - "8080:8080"
      - "7077:7077"
      - "5000:5000"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  spark-worker-a:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-a
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      # - SPARK_WORKER_CORES=5
      # - SPARK_WORKER_MEMORY=1G
      # - SPARK_DRIVER_MEMORY=1G
      
  # spark-worker-b:
  #   image: bde2020/spark-worker:3.0.0-hadoop3.2
  #   container_name: spark-worker-b
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_DRIVER_MEMORY=1G
      
  # spark-worker-c:
  #   image: bde2020/spark-worker:3.0.0-hadoop3.2
  #   container_name: spark-worker-c
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_DRIVER_MEMORY=1G
      
  spark-notebook:
    image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
    container_name: spark-notebook
    env_file:
      - ./hadoop.env
    ports:
      - 9001:9001
    depends_on:
      - spark-master
      - namenode
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      
  jupyter-notebook:
    container_name: jupyter-notebook
    image: dimajix/jupyter-spark:latest
    command: notebook
    # build:
    #   context:  .
    #   args:
    #     http_proxy: ${http_proxy}
    #     https_proxy: ${https_proxy}
    env_file:
      - ./hadoop.env
    environment:
      # - http_proxy=${http_proxy}
      # - https_proxy=${https_proxy}
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - 8888:8888
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - es-net

#  airflow-webserver:
#    image: apache/airflow:2.0.0
#    container_name: airflow-webserver
#    environment:
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////root/airflow/airflow.db
#      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#    ports:
#      - "8082:8080"
#    volumes:
#      - ./airflow-dags:/opt/airflow/dags
#    networks:
#      - es-net
#
#  airflow-scheduler:
#    image: apache/airflow:2.0.0
#    container_name: airflow-scheduler
#    command: scheduler
#    environment:
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////root/airflow/airflow.db
#      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#    volumes:
#      - ./airflow-dags:/opt/airflow/dags
#    networks:
#      - es-net
#
#  airflow-worker:
#    image: apache/airflow:2.0.0
#    container_name: airflow-worker
#    command: worker
#    environment:
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////root/airflow/airflow.db
#      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#    volumes:
#      - ./airflow-dags:/opt/airflow/dags
#    networks:
#      - es-net
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_INITDB_ARGS: --auth-host=trust
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./src/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - es-net
  redis:
    image: redis:latest
    container_name: airflow-redis
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - es-net

  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8086:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      retries: 5
    restart: always
    depends_on:
      - redis
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgres://airflow:airflow@postgres:5432/airflow

    volumes:
      - ./src:/opt/airflow/src
      - ./airflow:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - es-net

  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    command: scheduler
    restart: always
    depends_on:
      - redis
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgres://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./src:/opt/airflow/src
      - ./airflow:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - es-net

  airflow-worker:
    build: ./airflow
    container_name: airflow-worker
    command: celery worker
    restart: always
    depends_on:
      - redis
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgres://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./src:/opt/airflow/src
      - ./airflow:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - es-net

  airflow-init:
    build: ./airflow
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        airflow db init
        airflow users create \
            --username admin \
            --password admin \
            --firstname Admin \
            --lastname Admin \
            --role Admin \
            --email admin@example.com
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgres://airflow:airflow@postgres:5432/airflow
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
    volumes:
      - ./airflow:/sources
    networks:
      - es-net


  animetv-frontend-dev:
      build:
        context: ./frontend
        dockerfile: Dockerfile.dev
      container_name: animetv-frontend-dev
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
      networks:
        - es-net

  minio:
    image: minio/minio
    ports:
      - "9005:9000"
      - "9002:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - es-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    depends_on:
      - postgres
      - minio
    ports:
      - "5005:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
#    command: mlflow server --backend-store-uri file:///mlflow-data --default-artifact-root file:///mlflow-artifacts --host 0.0.0.0
    command: mlflow server --backend-store-uri file:///mlflow-data --default-artifact-root s3://mlflow/ --host 0.0.0.0
    volumes:
      - ./mlflow/data:/mlflow-data
    networks:
      - es-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - es-net

  fastapi:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
      - postgres
    restart: always
    volumes:
      - ./src:/opt/airflow/src
      - ./airflow/cache:/opt/airflow/cache
    environment:
      DATABASE_URL: postgresql://airflow:airflow@airflow-postgres:5432/ptpm
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - es-net
volumes:
  esdata:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  postgres-db-volume:
  minio-data:

networks:
  es-net:
    driver: bridge
